// apps/web/src/views/Landing/Faq.tsx
import { VStack, Heading } from '@chakra-ui/react';
import React from 'react';
import { Accordion } from '../../components';

const faqs = [
    {
        question: 'What is Saturday Hacknight?',
        answer: 'Saturday Hack Night is a biweekly hackathon organized by TinkerHub. The focus of the event is to provide learners the opportunity to explore a unique API and build exciting projects. TinkerHub will provide any credits or mentorship needed while you only have to think of one thing, Build!',
    },
    {
        question: 'Who can Participate?',
        answer: 'Anyone who is interested in learning and building something new. You can be a student, a professional, or a hobbyist. All you need is a laptop and an internet connection.',
    },
    {
        question: 'What should be the team size?',
        answer: 'You can work individually or in a team of 2-4 members.',
    },
    {
        question: 'What is the schedule of the program?',
        answer: ' The program will be conducted on every odd Saturday from 06:00 PM to 11:00 PM IST.',
    },
    {
        question: 'Still have questions?',
        answer: 'Feel free to reach out to us at hi@tinkerhub.org or in our Discord server.',
    },
];

const Faq = () => (
    <VStack width="100vw">
        <Heading
            fontFamily="Clash Display"
            textColor="white"
            textAlign="left"
            width="100vw"
            paddingInline="36px"
            fontSize="40px"
            marginBlockEnd="36px"
        >
            FREQUENTLY ASKED{' '}
            <span
                style={{
                    color: '#DBF72C',
                }}
            >
                QUESTIONS 💬
            </span>
        </Heading>
        <Accordion content={faqs} />
    </VStack>
);
export default Faq;

// src/components/Faq.vue
<template>
  <div class="faq md:-mt-20 mt-20" id="faq">
    <h3 class="text-3xl text-ash-gray">FAQ</h3>
    <div class="faq-item mt-7" v-for="faq in faqs" :key="faq.title">
        <p class="text-2xl font-mono  text-ash-gray">{{ faq.title }}</p>
        <p class="mt-2">{{ faq.value }}</p>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      faqs: [
        {
          title: "What is Saturday Hack Night?",
          value:
            "Saturday Hack Night is a biweekly hackathon organized by TinkerHub. The focus of the event is to provide learners the opportunity to explore a unique API and build exciting projects. TinkerHub will provide any credits or mentorship needed while you only have to think of one thing, Build!",
          category: "Tab-1",
        },
        {
          title: "Who can participate?",
          value:
            "You. Are you passionate about tech? Do you like to build something unique? Are you that curious cat who loves to explore uncharted territory? Then this is your opportunity.",
          category: "Tab-1",
        },
        {
          title: "What should the team size be?",
          value:
            "Individual or maximum 3 members. You can participate on your own or team-up with your friends, the more the merrier, right?",
          category: "Tab-1",
        },
        {
          title: "What is the schedule of the program?",
          value:
            "Saturday evening 6 PM to 11 PM every odd saturday you will be able to take part in the program. Yes it is a recurring event and yes, you are welcome every time.",
          category: "Tab-1",
        },
        {
          title: "Still have questions?",
          value:
            "Contact our core team - you can get in tough with us on our Discord channel (you will be added on registration) or ping us directly.",
          category: "Tab-1",
        },
      ],
    };
  },
};
</script>

<style></style>
